<script lang="ts">
    import type {ProjectPlan} from "./types/ProjectPlan.ts";
    import type {ProjectTask} from "./types/ProjectTask.ts";
    import type {ExplanationTab} from "./types/ExplanationTab.ts";

    export let projectPlan: ProjectPlan;
    export let tabs: ExplanationTab[];
    export let openTaskTab: (task: ProjectTask) => void;
    function downloadMarkdown() {
        if (!projectPlan) return;

        let mdContent = `# ${projectPlan.project_name}\n\n`;
        mdContent += `**Generated by DevStep.ai**\n\n`;
        mdContent += `**Tech Stack:** ${projectPlan.suggested_stack.join(', ')}\n\n`;
        mdContent += `---\n\n`;

        projectPlan.tasks.forEach((task, index) => {
            mdContent += `## Step ${index + 1}: ${task.title}\n\n`;
            mdContent += `${task.description}\n\n`;
            mdContent += `> **Technical Hint:** ${task.technical_hint}\n\n`;

            const detailedTab = tabs.find(t => t.id === task.title && t.data);
            if (!detailedTab) return
            if (detailedTab) {
                mdContent += `### 👨‍💻 Mentor's Guide\n\n`;
                mdContent += `${detailedTab.data?.explanation}\n\n`;
                mdContent += "```\n" + detailedTab.data?.code_snippet + "\n```\n\n";

                if (detailedTab.data?.related_docs && detailedTab.data.related_docs.length > 0) {
                    mdContent += `**Learn more:** ${detailedTab.data?.related_docs?.join(', ')}\n\n`;
                }
            }

            mdContent += `---\n\n`;
        });

        const blob = new Blob([mdContent], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');

        const safeName = projectPlan.project_name.replace(/[^a-z0-9]/gi, '_').toLowerCase();

        a.href = url;
        a.download = `${safeName}_blueprint.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
</script>

<div class="animate-fade-in-up my-5">

    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-3 gap-4">
            <h2 class="text-2xl font-bold">{projectPlan.project_name}</h2>
            <button
                    on:click={downloadMarkdown}
                    class="flex items-center cursor-pointer gap-2 px-4 py-2 bg-yale-blue text-white text-sm font-medium rounded-lg hover:bg-stormy-teal transition shadow-sm"
            >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                Export to .MD
            </button>
    </div>
    <div class="flex gap-2 flex-wrap justify-start mb-3">
        {#each projectPlan.suggested_stack as tech}
              <span class="px-3 py-1 bg-yale-blue text-alabaster-grey text-xs font-semibold rounded-full">
                {tech}
              </span>
        {/each}
    </div>
    <div class="relative border-l-2 border-stormy-teal ml-4 space-y-8">
        {#each projectPlan.tasks as task, i}
            <div class="relative pl-8">
                <div class="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-yale-blue border-4 border-alabaster-grey shadow-sm"></div>

                <div class="bg-white p-5 rounded-lg shadow-sm border border-gray-200 hover:shadow-md transition group">
                    <div class="flex justify-between items-start">
                        <div class="text-left">
                            <h3 class="text-lg font-bold text-gray-800">Step {i + 1}: {task.title}</h3>
                            <p class="text-gray-600 mt-1">{task.description}</p>
                            <p class="text-xs text-gray-400 mt-2 font-mono">💡
                                Hint: {task.technical_hint}</p>
                        </div>

                        <button
                                on:click={() => openTaskTab(task)}
                                class="ml-4 p-2 text-yale-blue hover:bg-blue-50 rounded-full transition tooltip cursor-pointer"
                                title="How do I do this?"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                 viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <circle cx="12" cy="12" r="10"/>
                                <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/>
                                <path d="M12 17h.01"/>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        {/each}
    </div>
</div>